### ISSUE TITLE
How do i set it up

### ISSUE THREAD

**Issue by clemencyworld1** [marcof-nikogo/metacity-decor#1]
I have successfuly built and installed metacity-decor. I also downloadé a gnome tgeme that includes metacity tbeme. I set the theme using lxappearance. Then i put the name of the metacìy theme in theme section of the plugin using wcm. I actovated the plugin but nothing happened. Seems am not doing something right.

Please help me have the correct setup.
Thanks

**Comment by liumingedwin** [comment]
You should set the theme through wayfire.ini

**Comment by liumingedwin** [comment]
In addition, use `\#` instead of `#`

**Comment by clemencyworld1** [comment]
Thanks for your response. Please what's the configuration syntax to set matacity theme in wayfire.ini

**Comment by liumingedwin** [comment]
See metadata/metacity-decor.xml

**Comment by clemencyworld1** [comment]
Thanks a lot. I got it set up and working perfectly. Awesome!

**Comment by clemencyworld1** [comment]
Built on Debian stable against wayfire 0.8.0
